### ISSUE TITLE
Card sound briefly heard on Reset All in Standard PhET-iO wrapper with FF

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#582]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/993, I'm only seeing this with FF:
In the Standard PhET-iO wrapper and downstream sim of State wrapper, the card sound is heard when pressing Reset All if the sim was launched with the balls already kicked. If the sim is launched with 5 or less balls kicked, I don't see this issue. 
Not sure if this is worth the time to address.

**Steps to reproduce**
1. In Studio, kick all 15 balls on the Median Screen
2. Press Test
3. Move a card in the Standard PhET-iO wrapper (or check the Sort checkbox)
4. Press Reset All

**Visuals**

https://github.com/phetsims/center-and-variability/assets/87318828/5c5ed9ad-963f-48ab-8f59-d14bf12e2abc

**Comment by marlitas** [comment]
I'm going to ask @catherinecarter about priority and time threshold on this before I begin investigating.

**Comment by catherinecarter** [comment]
This same issue was happening across the board in previous versions, and was fixed for most browsers. If this is only happening in FF, I'm concerned this will be challenging and time consuming to find. 

IMHO, the sound is super brief and minorly distracting, so I recommend spending minimal time to investigate, and if not found quickly, to let it be.

**Comment by samreid** [comment]
Experimenting with this patch:

<details>

```diff

Subject: [PATCH] Move ChangeIOType to a separate file, see https://github.com/phetsims/phet-io-wrappers/issues/572
---
Index: center-and-variability/js/median/model/InteractiveCardContainerModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/center-and-variability/js/median/model/InteractiveCardContainerModel.ts b/center-and-variability/js/median/model/InteractiveCardContainerModel.ts
--- a/center-and-variability/js/median/model/InteractiveCardContainerModel.ts	(revision ae16afe402ac8f5ec70974758e2b3d63053d8aaa)
+++ b/center-and-variability/js/median/model/InteractiveCardContainerModel.ts	(date 1697731562825)
@@ -33,6 +33,8 @@
 import dotRandom from '../../../../dot/js/dotRandom.js';
 import CAVQueryParameters from '../../common/CAVQueryParameters.js';
 import Emitter from '../../../../axon/js/Emitter.js';
+import isResettingProperty from '../../../../soccer-common/js/model/isResettingProperty.js';
+import isSettingPhetioStateProperty from '../../../../tandem/js/isSettingPhetioStateProperty.js';
 
 const cardMovementSounds = [
   cardMovement1_mp3,
@@ -83,6 +85,7 @@
   // Property that is triggered via focus and blur events in the InteractiveCardNodeContainer
   public readonly isKeyboardFocusedProperty = new BooleanProperty( false );
   public readonly manuallySortedEmitter: Emitter;
+  private stepsSinceReset = 0;
 
   public constructor( medianModel: MedianModel, providedOptions: InteractiveCardContainerModelOptions ) {
     super( medianModel, providedOptions );
@@ -163,6 +166,13 @@
       tandem: providedOptions.tandem.createTandem( 'manuallySortedEmitter' ),
       phetioFeatured: true
     } );
+
+    isResettingProperty.link( () => {
+      this.stepsSinceReset = 0;
+    } );
+    isSettingPhetioStateProperty.link( () => {
+      this.stepsSinceReset = 0;
+    } );
   }
 
   /**
@@ -221,12 +231,17 @@
 
         const randomClip = availableSoundClips[ dotRandom.nextInt( availableSoundClips.length ) ];
 
-        // Moving to the right, go up in pitch by 4 semitones
-        randomClip.setPlaybackRate( CAVQueryParameters.cardMovementSoundPlaybackRate *
-                                    ( directionToPlay === 'left' ? 1 :
-                                      directionToPlay === 'right' ? Math.pow( 2, 4 / 12 ) :
-                                      directionToPlay === 'both' ? Math.pow( 2, 2 / 12 ) : 0 ) );
-        randomClip.play();
+        if ( !isResettingProperty.value && !isSettingPhetioStateProperty.value && this.stepsSinceReset > 1 ) {
+
+          console.log( this.stepsSinceReset );
+
+          // Moving to the right, go up in pitch by 4 semitones
+          randomClip.setPlaybackRate( CAVQueryParameters.cardMovementSoundPlaybackRate *
+                                      ( directionToPlay === 'left' ? 1 :
+                                        directionToPlay === 'right' ? Math.pow( 2, 4 / 12 ) :
+                                        directionToPlay === 'both' ? Math.pow( 2, 2 / 12 ) : 0 ) );
+          randomClip.play();
+        }
       }
     } );
 
Index: tambo/js/sound-generators/SoundClip.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tambo/js/sound-generators/SoundClip.ts b/tambo/js/sound-generators/SoundClip.ts
--- a/tambo/js/sound-generators/SoundClip.ts	(revision d5406de1572c122790318046a0b645baa5faedc6)
+++ b/tambo/js/sound-generators/SoundClip.ts	(date 1697730704224)
@@ -166,6 +166,8 @@
    */
   public play( delay = 0 ): void {
 
+    console.log( new Error().stack );
+
     if ( this.audioContext.state === 'running' && this.wrappedAudioBuffer.audioBufferProperty.value ) {
 
       const now = this.audioContext.currentTime;

```

</details>

**Comment by marlitas** [comment]
@jbphet and I found what seemed to be a simple solution that mostly solves the problem. It's at least significantly less noticeable now. We feel this fix is good enough for this rare and specific scenario.

**Comment by samreid** [comment]
In my testing, that proposal does not solve the problem. It doesn't work because the sound is not triggered during a reset.

**Comment by marlitas** [comment]
@jbphet and I tested the proposed fix in both Chrome and Firefox and got identical results in both. We were no longer able to here the remnant card sound and only had the small clipping sound that is being tracked by https://github.com/phetsims/tambo/issues/159. Fixing the clipping is beyond the scope of this sim. We were not able to determine why behavior was different in Firefox vs. Chrome, but decided that the priority of this issue did not warrant further exploration.

@samreid how would you like to proceed?

**Comment by marlitas** [comment]
I tried this most recent commit various time on firefox with logging to track the lifecycle of the Property and it seems to be working as we'd expect. I will cherry-pick this commit in, however if it does not fix the problem on firefox we have used up our allotted time on this issue and it should be closed either way.

**Comment by marlitas** [comment]
@Nancy-Salpepi or @KatieWoe when testing for this next RC, go ahead and close even if the problem isn't completely resolved. We have spent too much time investigating and trying a fix. Leave open if the problem has gotten worse or perhaps there are side effects, otherwise we're going to say it's completed.

**Comment by Nancy-Salpepi** [comment]
I'm not hearing the card sound with mac + FF/safari/chrome. 
I'm going to close.
